FROM ibmjava:8

WORKDIR /usr/src/app
COPY target/*.jar ./app.jar

ENTRYPOINT ["java","-XX:+UnlockExperimentalVMOptions","-XX:+UseCGroupMemoryLimitForHeap","-XX:MaxRAMFraction=1","-XX:+UseG1GC","-Djava.security.egd=file:/dev/urandom","-jar","./app.jar", "--port=8080"]



